function titles = DataSet3ColumnHeaders()

titles = {
    'Date'
    'Experiment Name'	
    'Experiment Title'	
    'Time Stamp'	
    'Slide No.'	
    'Worm ID'
    'Experiment No.'	
    'Strain'	
    'Treatments'	
    'Gender'	
    'Age'	
    'Percent Agar'	
    'Food Status'	
    'Cantilever ID'	
    'Frequency (kHz)'	
    'Stiffness (N/m)'	
    'Sensitivity (um/V)'	
    'P Parameter'	
    'I Parameter'	
    'D Parameter'	
    'Temp'	
    'Humidity'	
    'Experiment Mode'	
    'Experiment Comments'	
    'Post Experiment Comments'	
    'Pre Stim Recording Time (s)'	
    'Post Stim Recording Time (s)'	
    'Stimulus Number'	
    'Stimulus First Frame Time'	
    'Stimulus Approach On Time'	
    'Stimulus Start Time'	
    'Stimulus End Time'	
    'Stimulus Magnitude (nN)'	
    'Stimulus Duration (t)'	
    'Stimulus Duration (t)'	
    'Soft Balance Value (V)'	
    'Approach Duration (s)'	
    'Stimulus FPGA Start Time (s)'
    'Stimulus RMS Error'	
    'Stimulus Rise Time (s)'	
    'Stimulus Settling Time (s)'	
    'Stimulus Value (V)'	
    'Zero Pulse Duration (s)'	
    'Zero Pulse Average (V)'	
    'Zero Pulse RMS Error'	
    'Zero Pulse Min'
    'Zero Pulse Min Time'
    'Pull off Voltage (V)'	
    'Reported Force (nN)'	
    'Reported Cantilever Deflection (um)'	
    'Reported Indentation (um)'	
%     'Reported Force (nN) (recalibration)'	
%     'Reported Cantilever Deflection (um) (recalibration)'	
%     'Reported Indentation (um) (recalibration)'
    'Number of Bad Frames'	
    'Average Body length (um)'	
    'STD Body Length (um)'	
    'Average Body Width (um)'	
    'STD Body Width (um)'	
    'Filtered Average Body length (um)'	
    'Filtered STD Body Length (um)'	
    'Filtered Average Body Width (um)'	
    'Filtered STD Body Width (um)'	
    'Pre Stim Amplitude (um)'	
    'Pre Stim Wavelength (um/cycle)'	
    'Post Stim Amplitude (um)'	
    'Post Stim Wavelength (um/cycle)'	
    'Target Location (%)'	
    'Distance from Target (um)'	
    'Percent Down Body Hit (%)'
    'Distance from Skeleton (um)'	
%     'Percent Across Body Hit (%)'	
%     'Pre Stim Fit a'	
%     'Pre Stim Fit b'	
%     'Pre Stim Fit c'	
%     'Pre Stim Fit d'	
%     'Pre Stim Fit goodness (rmse)'	
%     'Post Stim Fit a'	
%     'Post Stim Fit b'	
%     'Post Stim Fit c'	
%     'Post Stim Fit d'	
%     'Post Stim Fit goodness (rmse)'	
    'Pre Stimulus Average Speed (um/s)'	
    'Post Stimulus Average Speed (um/s)'	
    'Post Stimulus Average Speed 2 (um/s)'	
    'Trial Success Scoring'	
    'Trial Success?'	
    'Response Type'	
    'Any Response?'	
    'Response Latency (s)'	
    'Max Response Speed (um/s)'
    'Max Response Acceleration (um/s^2)'
    'Response Type 2'
    'Max Response Acceleration 2 (um/s^2)'
    'Response Type 3'
    'Response Type 4'
    'Reversal Acceleration'
    'Reversal Duration Flag'
    'Reversal Duration'
    'Pre Reversal Speed'
    'Post Reversal Speed'
    'Reversal On Frame'
    'Reversal Off Frame'
    'Reversal On Orientation'
    'Reversal Off Orientation'
    'Pre Stim Amplitude (% Body Length)'	
    'Pre Stim Wavelength (%Body Length/cycle)'	
    'Post Stim Amplitude (%Body Length)'	
    'Post Stim Wavelength (%Body Length/cycle)'	    
    '% Change Amplitude'	
    '% Change Wavelength'	
    '% Change in Speed' };		
end