

function titles = getBehaviorTitles()

titles = {
    'Date'
    'Experiment Name'
    'Experiment Title'	
    'Time Stamp'
    'Slide No.'
    'Experiment No.'
    'Strain'
    'Treatments'
    'Gender'
    'Age'
    'Percent Agar'
    'Food Status'
    'Temp'
    'Humidity'
    'Experiment Mode'
    'Experiment Comments'
    'Post Experiment Comments'
    'Pre Stim Recording Time (s)'	
    'Post Stim Recording Time (s)'
    'Stimulus Number'
    'Stimulus First Frame Time'
    'Stimulus Start Time'
    'Stimulus End Time'
    'Average Body length (um)'
    'STD Body Length (um)'
    'Average Body Width (um)'
    'STD Body Width (um)'
    'Filtered Average Body length (um)'
    'Filtered STD Body Length (um)'
    'Filtered Average Body Width (um)'
    'Filtered STD Body Width (um)'
    'Target Location (%)'
    'Distance from Target (um)'
    'Percent Down Body Hit (%)'
    'Distance from Skeleton (um)'
    'Percent Across Body Hit (%)'
    'Stimulus Duration (t)'
    'Number of Bad Frames'        
    'Pre Stim Fit a'
    'Pre Stim Fit b'
    'Pre Stim Fit c'
    'Pre Stim Fit d'
    'Pre Stim Fit goodness (rmse)'
    'Post Stim Fit a'
    'Post Stim Fit b'
    'Post Stim Fit c'
    'Post Stim Fit d'
    'Post Stim Fit goodness (rmse)'
    'Average Track Velocity'
    'Average Mean Position Velocity'
    'Average Amplitude (um)'
    'Average Wavelength (um/cycle)'};
  


end