titles = {
'Date'	
'Experiment Name'	
'Experiment Title'	
'Time Stamp'	
'Slide No.'	
'Experiment No.'	
'Strain'
'Treatments'	
'Gender'	
'Age'	
'Percent Agar'	
'Food Status'	
'Cantilever ID'	
'Frequency (kHz)'	
'Stiffness (N/m)'	
'Sensitivity (um/V)'	
'P Parameter'	
'I Parameter'	
'D Parameter'	
'Temp'	
'Humidity'	
'Experiment Mode'	
'Experiment Comments'	
'Post Experiment Comments'	
'Pre Stim Recording Time (s)'	
'Post Stim Recording Time (s)'	
'Stimulus Number'	
'Stimulus First Frame Time'	
'Stimulus Approach On Time'	
'Stimulus Start Time'	
'Stimulus End Time'	
'Average Body length (um)'	
'STD Body Length (um)'	
'Average Body Width (um)'	
'STD Body Width (um)'	
'Filtered Average Body length (um)'	
'Filtered STD Body Length (um)'	
'Filtered Average Body Width (um)'	
'Filtered STD Body Width (um)'	
'Target Location (%)'	
'Distance from Target (um)'	
'Percent Down Body Hit (%)'	
'Distance from Skeleton (um)'	
'Percent Across Body Hit (%)'	
'Stimulus Magnitude (nN)'	
'Stimulus Duration (t)'	
'Stimulus Duration (t)'	
'Soft Balance Value (V)'	
'Approach Duration (s)'	
'Stimulus RMS Error'	
'Stimulus Rise Time (s)'	
'Stimulus Settling Time (s)'	
'Stimulus Value (V)'	
'Zero Pulse Duration (s)'	
'Zero Pulse Average (V)'	
'Zero Pulse RMS Error'	
'Pull off Voltage (V)'	
'Number of Bad Frames'	
'Trial Success Scoring'	
'Trial Success?'	
'Response Type'	
'Response Latency (s)'	
'Pre Stimulus Average Speed (um/s)'	
'Post Stimulus Average Speed (um/s)'
'Pre Stim Fit a'	
'Pre Stim Fit b'	
'Pre Stim Fit c'	
'Pre Stim Fit d'	
'Pre Stim Fit goodness (rmse)'	
'Post Stim Fit a'	
'Post Stim Fit b'
'Post Stim Fit c'	
'Post Stim Fit d'	
'Post Stim Fit goodness (rmse)'};