%%%% Function: Import Video
%  Sorts Tracking data by stimulus application for analysis
% 
%  param {directory} string, location of the video file created by HAWK
%  
%  returns {obj} Video struct,  an object containing all the information
%  about the video generated by HAWK
%
%  Copyright 2015 Eileen Mazzochette, et al <emazz86@stanford.edu>
%  This file is part of HAWK_AnalysisMethods.
%
%%%%%



function obj = importVideoFile(directory) 
    if (ispc) %if on PC workstation in MERL 223
        slash = '\';
    elseif (ismac) % if on Eileen's personal computer
        slash = '/';
    end
    %determine experiment title based on file name:
    for index = length(directory):-1:1
        if (directory(index) == slash)
            startTitleIndex = index+1;
            break;
        end
    end
    experimentTitle = directory(startTitleIndex:length(directory));

    % Read in video file to return.
    obj = VideoReader(fullfile(directory,strcat(experimentTitle,'_video.avi')));


end