function createfigure(X1, YMatrix1, titleOfPlot)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 02-Dec-2014 18:41:14

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,1,1,'Parent',figure1,'FontSize',16);
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'LineWidth',2);
set(plot1(1),'Color',[0.200000002980232 0.200000002980232 1],...
    'DisplayName','Piezoresistor Signal');
set(plot1(2),'Color',[0.87058824300766 0.490196079015732 0],...
    'DisplayName','Actuator Signal');

% Create title
title(titleOfPlot,'FontSize',20);

% Create xlabel
xlabel('Time (s)','FontSize',16);

% Create ylabel
ylabel({'Voltage (V)'},'FontSize',16);

% Create legend
legend(subplot1,'show');

